### ISSUE TITLE
zbundle auto update when a new flist is available

### ISSUE THREAD

**Issue by muhamadazmy** [zero-os/0-bundle#4]
Zbundle should restart the `bundle` when a new release of the flist is available.

**Comment by zaibon** [comment]
I checked the information return by the hub, and we can already retrieve the updated time of an flists like this:
```python
hub = j.clients.zerohub.get('main')
flists = hub.list('gig-official-apps')
```
`flists` is an array of dict like this:
```python
{'name': 'zero-os-gw-master.flist',
  'size': '953.17 KB',
  'type': 'regular',
  'updated': 1500116617}
```

We could use that to monitor when a new version of an flist is released and then restart the zbundle
